# Generated by Django 4.1.7 on 2023-03-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('level', models.SmallIntegerField(verbose_name='奖的等级')),
                ('num', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '奖品表',
                'db_table': 'raffle_prize',
            },
        ),
        migrations.CreateModel(
            name='WinningPrizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=20, verbose_name='匿名用户ip识别')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle.prizemodel')),
            ],
            options={
                'verbose_name': '中奖奖品表',
                'db_table': 'raffle_winningPrize',
            },
        ),
    ]
