# Generated by Django 4.1.7 on 2023-03-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizemodel',
            name='num',
            field=models.IntegerField(db_index=True, verbose_name='数量'),
        ),
    ]
