# Generated by Django 4.1.7 on 2023-03-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0002_alter_prizemodel_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizemodel',
            name='num',
            field=models.IntegerField(verbose_name='数量'),
        ),
    ]
