# Generated by Django 4.1.7 on 2023-03-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0003_alter_prizemodel_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizemodel',
            name='use_num',
            field=models.IntegerField(default=0, verbose_name='使用数量'),
        ),
    ]
