# Generated by Django 4.1.7 on 2023-03-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0004_prizemodel_use_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizemodel',
            name='use_num',
        ),
        migrations.AddField(
            model_name='prizemodel',
            name='surplus_num',
            field=models.IntegerField(default=0, verbose_name='剩余数量'),
        ),
    ]
