# Generated by Django 4.1.7 on 2023-03-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0005_remove_prizemodel_use_num_prizemodel_surplus_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizemodel',
            name='name',
            field=models.CharField(default=1, max_length=5, verbose_name='奖品名称'),
        ),
    ]
